###
curl -X POST http://localhost:8080/send-welcome-email \
-H "Content-Type: application/json" \
-d '{
  "email": "dagwanpan@gmail.com",
  "name": "John Doe",
  "link": "https://fakadinfotech.com"
}'

###
curl -X POST http://localhost:3000/send-welcome-email \
-H "Content-Type: application/json" \
-d '{
  "email": "dan21017@byui.edu",
  "name": "John Doe",
  "link": "https://fakadinfotech.com"
}'

###
curl -X POST http://localhost:3000/send-welcome-email \
-H "Content-Type: application/json" \
-d '{
  "email": "dagwanpan@outlook.com",
  "name": "John Doe",
  "link": "https://fakadinfotech.com"
}'

###
curl -X POST http://localhost:3000/send-welcome-email \
-H "Content-Type: application/json" \
-d '{
  "email": "dagwanpan@yahoo.com",
  "name": "John Doe",
  "link": "https://fakadinfotech.com"
}'
















# ###
# curl -X POST http://localhost:3000/api/email/send-welcome-email \
# -H "Content-Type: application/json" \
# -d '{
#   "email": "dagwanpan@gmail.com",
#   "name": "John Doe",
#   "link": "https://fakadinfotech.com",
#   "attachments": [
#     {
#       "filename": "welcome.jpg",
#       "path": "./public/images/welcome.jpg",
#       "cid": "welcome_image"
#     }
#   ]
# }'

# ###
# curl -X POST http://localhost:3000/api/email/send-welcome-email \
# -H "Content-Type: application/json" \
# -d '{
#   "email": "dan21017@byui.edu",
#   "name": "John Doe",
#   "link": "https://fakadinfotech.com",
#   "attachments": [
#     {
#       "filename": "welcome.jpg",
#       "path": "./public/images/welcome.jpg",
#       "cid": "welcome_image"
#     }
#   ]
# }'

# ###
# curl -X POST http://localhost:3000/api/email/send-welcome-email \
# -H "Content-Type: application/json" \
# -d '{
#   "email": "dagwanpan@outlook.com",
#   "name": "John Doe",
#   "link": "https://fakadinfotech.com",
#   "attachments": [
#     {
#       "filename": "welcome.jpg",
#       "path": "./public/images/welcome.jpg",
#       "cid": "welcome_image"
#     }
#   ]
# }'

# ###
# curl -X POST http://localhost:3000/api/email/send-welcome-email \
# -H "Content-Type: application/json" \
# -d '{
#   "email": "dagwanpan@yahoo.com",
#   "name": "John Doe",
#   "link": "https://fakadinfotech.com",
#   "attachments": [
#     {
#       "filename": "welcome.jpg",
#       "path": "./public/images/welcome.jpg",
#       "cid": "welcome_image"
#     }
#   ]
# }'
