###
curl -X POST http://localhost:8080/send-welcome-email \
-H "Content-Type: application/json" \
-d '{
  "email": ["dagwanpan@gmail.com"],
  "name": "John Doe",
  "link": "https://fakadinfotech.com"
}'

### with attachement
curl -X POST http://localhost:8080/send-welcome-email \
-H "Content-Type: application/json" \
-d '{
  "email": ["dagwanpan@gmail.com", "dagwanpan@outlook.com"],
  "name": "John Doe",
  "link": "https://fakadinfotech.com",
  "attachments": [
    {
      "filename": "logo.png",
      "path": "public/images/logo.jpg",
      "cid": "logo@fakad",
      "embed": true
    },
    {
      "filename": "another-image.png",
      "path": "public/images/logo.jpg",
      "cid": "image@fakad",
      "embed": true
    },
    {
      "filename": "document.pdf",
      "path": "public/docs/document.pdf",
      "embed": false
    }
  ]
}'




